const drivingTestPasses = [
    {
        name: "Samson",
        datePassed: "April 2025",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Kidbrooke",
        alt: "",
        img: "/img/test-passes/thumbnails/samson-wong.jpg",
        altText: "",
    },
    {
        name: "Pauliina",
        datePassed: "April 2025",
        testCentre: "Bromley",
        firstTime: true,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/pauliina-leskinen.jpg",
        altText: "",
    },
    {
        name: "Kate",
        datePassed: "February 2025",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Blackheath",
        alt: "",
        img: "/img/test-passes/thumbnails/kate-scott.jpg",
        altText: "",
    },
    {
        name: "Josh",
        datePassed: "February 2025",
        testCentre: "Bromley",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/josh-bauly.jpg",
        altText: "",
    },
    {
        name: "Marnie",
        datePassed: "January 2025",
        testCentre: "Bromley",
        firstTime: false,
        area: "Grove Park",
        alt: "",
        img: "/img/test-passes/thumbnails/marnie-ridley.jpg",
        altText: "",
    },
    {
        name: "Emma",
        datePassed: "January 2025",
        testCentre: "Bromley",
        firstTime: true,
        area: "Bromley",
        alt: "",
        img: "/img/test-passes/thumbnails/emma-mckenna.jpg",
        altText: "",
    },
    {
        name: "Jack",
        datePassed: "December 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "New Eltham",
        alt: "",
        img: "/img/test-passes/thumbnails/jack-garnham.jpg",
        altText: "",
    },
    {
        name: "Lilly",
        datePassed: "December 2024",
        testCentre: "Bromley",
        firstTime: false,
        area: "Bickley",
        alt: "",
        img: "/img/test-passes/thumbnails/lilly-geheren.jpg",
        altText: "",
    },
    {
        name: "Teddy",
        datePassed: "November 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Sidcup",
        alt: "",
        img: "/img/test-passes/thumbnails/teddy-parker.jpg",
        altText: "",
    },
    {
        name: "James",
        datePassed: "September 2024",
        testCentre: "Erith",
        firstTime: true,
        area: "Charlton",
        alt: "",
        img: "/img/test-passes/thumbnails/james-huthwaite.jpg",
        altText: "",
    },
    {
        name: "Alex",
        datePassed: "September 2024",
        testCentre: "Bromley",
        firstTime: true,
        area: "Grove Park",
        alt: "",
        img: "/img/test-passes/thumbnails/alex-abley.jpg",
        altText: "",
    },
    {
        name: "Rachel",
        datePassed: "August 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/rachel-cole-wilkin.jpg",
        altText: "",
    },
    {
        name: "Caroline",
        datePassed: "July 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/caroline-wadham.jpg",
        altText: "",
    },
    {
        name: "Amy",
        datePassed: "July 2024",
        testCentre: "Bromley",
        firstTime: false,
        area: "New Eltham",
        alt: "",
        img: "/img/test-passes/thumbnails/amy-watts.jpg",
        altText: "with zero driver faults",
    },
    {
        name: "Wilhemina",
        datePassed: "July 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Sidcup",
        alt: "",
        img: "/img/test-passes/thumbnails/wilhemina-konteh.jpg",
        altText: "with zero driver faults",
    },
    {
        name: "Angelika",
        datePassed: "June 2024",
        testCentre: "Bromley",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/angelika-gomolka.jpg",
        altText: "",
    },
    {
        name: "Rory",
        datePassed: "June 2024",
        testCentre: "Erith",
        firstTime: true,
        area: "Petts Wood",
        alt: "",
        img: "/img/test-passes/thumbnails/rory-charman.jpg",
        altText: "",
    },
    {
        name: "Amy",
        datePassed: "June 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/amy-campbell.jpg",
        altText: "",
    },
    {
        name: "Amelia",
        datePassed: "May 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Bickley",
        alt: "",
        img: "/img/test-passes/thumbnails/amelia-armitage.jpg",
        altText: "with only one driver fault",
    },
    {
        name: "Domantas",
        datePassed: "May 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/domantas.jpg",
        altText: "",
    },
    {
        name: "Callum",
        datePassed: "May 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Hither Green",
        alt: "",
        img: "/img/test-passes/thumbnails/callum-hc.jpg",
        altText: "",
    },
    {
        name: "Connor",
        datePassed: "May 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Orpington",
        alt: "",
        img: "/img/test-passes/thumbnails/connor-bussey.jpg",
        altText: "during school rush hour",
    },
    {
        name: "Atharv Gupta",
        datePassed: "March 2024",
        testCentre: "Bromley",
        firstTime: true,
        area: "Petts Wood",
        alt: "",
        img: "/img/test-passes/thumbnails/atharv-gupta.jpg",
        altText: "",
    },
    {
        name: "Adam",
        datePassed: "February 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Kidbrooke",
        alt: "",
        img: "/img/test-passes/thumbnails/adam-croxford.jpg",
        altText: "",
    },
    {
        name: "Chloe",
        datePassed: "January 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Petts Wood",
        alt: "",
        img: "/img/test-passes/thumbnails/chloe-steel.jpg",
        altText: "",
    },
    {
        name: "Kenneth",
        datePassed: "December 2023",
        testCentre: "Bromley",
        firstTime: true,
        area: "Bromley",
        alt: "Test passed with only one driving fault,",
        img: "/img/test-passes/thumbnails/kenneth-masceranhas.jpg",
        altText: "with one driving fault",
    },
    {
        name: "Cristiano",
        datePassed: "December 2023",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Chislehurst",
        alt: "Test passed with zero driving faults, Sidcup 2023",
        img: "/img/test-passes/thumbnails/cristiano-da-silva.jpg",
        altText: "with zero driving faults",
    },
    {
        name: "Besmir",
        datePassed: "November 2023",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Sidcup, November 2023",
        img: "/img/test-passes/thumbnails/besmir-hoxha.jpg",
    },
    {
        name: "Alex",
        datePassed: "November 2023",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Sidcup, November 2023",
        img: "/img/test-passes/thumbnails/alex-sibley.jpg",
    },
    {
        name: "Nyiah",
        datePassed: "April 2022",
        testCentre: "Hither Green",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Hither Green, April 2022",
        img: "/img/test-passes/thumbnails/nyiah-pilgrim.jpg",
    },
    {
        name: "Dylan",
        datePassed: "March 2022",
        testCentre: "Hither Green",
        firstTime: false,
        area: "University of Greenwich",
        alt: "Test passed in Hither Green, March 2022",
        img: "/img/test-passes/thumbnails/dylan-bassono.jpg",
    },
    {
        name: "Ellie",
        datePassed: "February 2022",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Sidcup, November 2021",
        img: "/img/test-passes/thumbnails/ellie-daniels.jpg",
    },
    {
        name: "Ashley",
        datePassed: "November 2021",
        testCentre: "Bromley",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Bromley, November 2021",
        img: "/img/test-passes/thumbnails/ashley-hooker.jpg",
    },
    {
        name: "Loryn",
        datePassed: "November 2021",
        testCentre: "Bromley",
        firstTime: true,
        area: "New Eltham",
        alt: "Test passed in Bromley, November 2021",
        img: "/img/test-passes/thumbnails/loryn-hunt.jpg",
    },
    {
        name: "Amy",
        datePassed: "November 2021",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Lee Green",
        alt: "Test passed in Sidcup, November 2021",
        img: "/img/test-passes/thumbnails/amy-smith.jpg",
    },
    {
        name: "Charlotte",
        datePassed: "November 2021",
        testCentre: "Sidcup",
        firstTime: true,
        area: "New Eltham",
        alt: "Test passed in Sidcup, November 2021",
        img: "/img/test-passes/thumbnails/charlotte-reid.jpg",
    },
    {
        name: "Katie",
        datePassed: "October 2021",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Eltham",
        alt: "Test passed in Sidcup, August 2021",
        img: "/img/test-passes/thumbnails/katie-clarkstone.jpg",
    },
    {
        name: "Callum",
        datePassed: "August 2021",
        testCentre: "Bromley",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Bromley, August 2021",
        img: "/img/test-passes/thumbnails/callum-biggins.jpg",
    },
    {
        name: "Dan",
        datePassed: "July 2021",
        testCentre: "Bromley",
        firstTime: false,
        area: "central London",
        alt: "Test passed in Bromley, July 2021",
        img: "/img/test-passes/thumbnails/dan-rosenheck.jpg",
        altText: "on a sunny Thursday morning",
        id: 10,
    },
    {
        name: "Lucas",
        datePassed: "May 2021",
        testCentre: "Bromley",
        firstTime: true,
        area: "Hither Green",
        alt: "Test passed in Bromley, May 2021",
        img: "/img/test-passes/thumbnails/lucas-dunckley.jpg",
        id: 9,
    },
    {
        name: "Rebecca",
        datePassed: "November 2020",
        testCentre: "Bromley",
        firstTime: false,
        area: "Chislehurst",
        alt: "Test passed in Chislehurst, October 2020",
        img: "/img/test-passes/thumbnails/rebecca-boley.png",
        id: 8,
        altText: "just before lockdown #2",
    },
    {
        name: "Ruby",
        datePassed: "October 2020",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Eltham",
        alt: "Test passed in Sidcup, October 2020",
        img: "/img/test-passes/thumbnails/ruby-kessell.png",
        id: 7,
        altText: "in the pouring rain",
    },
    {
        name: "Harry",
        datePassed: "March 2020",
        testCentre: "Bromley",
        firstTime: false,
        area: "Chislehurst",
        alt: "Test passed in Bromley, March 2020",
        img: "/img/test-passes/thumbnails/harry-bryant.png",
        id: 6,
        altText: "with only two driver faults",
    },
    {
        name: "Dominic",
        datePassed: "March 2020",
        testCentre: "Bromley",
        firstTime: false,
        area: "Sidcup",
        alt: "Test passed in Bromley, March 2020",
        img: "/img/test-passes/thumbnails/dominic-mcmillan.png",
        id: 5,
        altText: "in torrential rain",
    },
    {
        name: "Jack",
        datePassed: "February 2020",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Petts Wood",
        alt: "Test passed in Sidcup, Feb 2020",
        img: "/img/test-passes/thumbnails/jack-bennett.png",
        id: 4,
        altText: "",
    },
    {
        name: "Freddy",
        datePassed: "January 2020",
        testCentre: "Hither Green",
        firstTime: true,
        area: "Catford",
        alt: "Test passed in Hither Green, Jan 2020",
        img: "/img/test-passes/thumbnails/freddy-dalby-bowler.png",
        id: 3,
    },
    {
        name: "Dominic",
        datePassed: "January 2020",
        testCentre: "Hither Green",
        firstTime: true,
        area: "Blackheath",
        alt: "Test passed in Hither Green, Jan 2020",
        img: "/img/test-passes/thumbnails/dominic-johnson.png",
        id: 2,
        "alt-text": "",
    },
    {
        name: "Rose",
        datePassed: "January 2020",
        testCentre: "Hither Green",
        firstTime: true,
        area: "Kidbrooke",
        alt: "Test passed in Hither Green, Jan 2020",
        img: "/img/test-passes/thumbnails/rose-smith.png",
        id: 1,
        "alt-text": "",
    },
];

export default drivingTestPasses;
