const drivingTestPasses = [
    {
        name: "Viktor",
        datePassed: "April 2026",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/viktor-goloubovsky.webp",
        altText: "",
    },
    {
        name: "Olivia",
        datePassed: "March 2026",
        testCentre: "Sidcup",
        firstTime: false,
        area: "New Eltham",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/olivia-guyver.webp",
        altText: "",
    },
    {
        name: "Charles",
        datePassed: "March 2026",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/charles-murphy.webp",
        altText: "",
    },
    {
        name: "Kaitlin",
        datePassed: "January 2026",
        testCentre: "Sidcup",
        firstTime: true,
        area: "New Eltham",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/kaitlin-spencer.webp",
        altText: "",
    },
    {
        name: "Poppy",
        datePassed: "December 2025",
        testCentre: "Bromley",
        firstTime: true,
        area: "Grove Park",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/poppy-burgess.webp",
        altText: "",
    },
    {
        name: "Nyle",
        datePassed: "November 2025",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Grove Park",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/nyle-somers.webp",
        altText: "",
    },
    {
        name: "Molly",
        datePassed: "November 2025",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/molly-etheridge.webp",
        altText: "",
    },
    {
        name: "Rebecca",
        datePassed: "October 2025",
        testCentre: "Sidcup",
        firstTime: true,
        area: "New Eltham",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/rebecca-clossick.webp",
        altText: "",
    },
    {
        name: "Alex",
        datePassed: "September 2025",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/alex-rochester.webp",
        altText: "",
    },
    {
        name: "Thresa",
        datePassed: "September 2025",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Petts Wood",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/thresa-mathew.webp",
        altText: "",
    },
    {
        name: "Josh",
        datePassed: "September 2025",
        testCentre: "Bromley",
        firstTime: false,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/josh-mundy.webp",
        altText: "",
    },
    {
        name: "Jess",
        datePassed: "September 2025",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/jess-makahon.webp",
        altText: "",
    },
    {
        name: "Simi",
        datePassed: "September 2025",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/simi.webp",
        altText: "",
    },
    {
        name: "Amelia",
        datePassed: "June 2025",
        testCentre: "Bromley",
        firstTime: true,
        area: "Shooters Hill",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/amelia-cesenek.webp",
        altText: "",
    },
    {
        name: "Will",
        datePassed: "June 2025",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Petts Wood",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/will-magee-brown.webp",
        altText: "",
    },
    {
        name: "Charmaine",
        datePassed: "June 2025",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/charmaine-magay.webp",
        altText: "",
    },
    {
        name: "Samson",
        datePassed: "April 2025",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Kidbrooke",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/samson-wong.webp",
        altText: "",
    },
    {
        name: "Pauliina",
        datePassed: "April 2025",
        testCentre: "Bromley",
        firstTime: true,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/pauliina-leskinen.webp",
        altText: "",
    },
    {
        name: "Kate",
        datePassed: "February 2025",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Blackheath",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/kate-scott.webp",
        altText: "",
    },
    {
        name: "Josh",
        datePassed: "February 2025",
        testCentre: "Bromley",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/josh-bauly.webp",
        altText: "",
    },
    {
        name: "Marnie",
        datePassed: "January 2025",
        testCentre: "Bromley",
        firstTime: false,
        area: "Grove Park",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/marnie-ridley.webp",
        altText: "",
    },
    {
        name: "Emma",
        datePassed: "January 2025",
        testCentre: "Bromley",
        firstTime: true,
        area: "Bromley",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/emma-mckenna.webp",
        altText: "",
    },
    {
        name: "Jack",
        datePassed: "December 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "New Eltham",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/jack-garnham.webp",
        altText: "",
    },
    {
        name: "Lilly",
        datePassed: "December 2024",
        testCentre: "Bromley",
        firstTime: false,
        area: "Bickley",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/lilly-geheren.webp",
        altText: "",
    },
    {
        name: "Teddy",
        datePassed: "November 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Sidcup",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/teddy-parker.webp",
        altText: "",
    },
    {
        name: "James",
        datePassed: "September 2024",
        testCentre: "Erith",
        firstTime: true,
        area: "Charlton",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/james-huthwaite.webp",
        altText: "",
    },
    {
        name: "Alex",
        datePassed: "September 2024",
        testCentre: "Bromley",
        firstTime: true,
        area: "Grove Park",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/alex-abley.webp",
        altText: "",
    },
    {
        name: "Rachel",
        datePassed: "August 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/rachel-webp/cole-wilkin.webp",
        altText: "",
    },
    {
        name: "Caroline",
        datePassed: "July 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Chislehurst",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/caroline-wadham.webp",
        altText: "",
    },
    {
        name: "Amy",
        datePassed: "July 2024",
        testCentre: "Bromley",
        firstTime: false,
        area: "New Eltham",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/amy-watts.webp",
        altText: "with zero driver faults",
    },
    {
        name: "Wilhemina",
        datePassed: "July 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Sidcup",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/wilhemina-konteh.webp",
        altText: "with zero driver faults",
    },
    {
        name: "Angelika",
        datePassed: "June 2024",
        testCentre: "Bromley",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/angelika-gomolka.webp",
        altText: "",
    },
    {
        name: "Rory",
        datePassed: "June 2024",
        testCentre: "Erith",
        firstTime: true,
        area: "Petts Wood",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/rory-charman.webp",
        altText: "",
    },
    {
        name: "Amy",
        datePassed: "June 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/amy-campbell.webp",
        altText: "",
    },
    {
        name: "Amelia",
        datePassed: "May 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Bickley",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/amelia-armitage.webp",
        altText: "with only one driver fault",
    },
    {
        name: "Domantas",
        datePassed: "May 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Mottingham",
        alt: "",
        img: "/img/test-passes/webp/thumbnails/domantas.webp",
        altText: "",
    },
    {
        name: "Callum",
        datePassed: "May 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Hither Green",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/callum-hc.webp",
        altText: "",
    },
    {
        name: "Connor",
        datePassed: "May 2024",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Orpington",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/connor-bussey.webp",
        altText: "during school rush hour",
    },
    {
        name: "Atharv Gupta",
        datePassed: "March 2024",
        testCentre: "Bromley",
        firstTime: true,
        area: "Petts Wood",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/atharv-gupta.webp",
        altText: "",
    },
    {
        name: "Adam",
        datePassed: "February 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Kidbrooke",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/adam-croxford.webp",
        altText: "",
    },
    {
        name: "Chloe",
        datePassed: "January 2024",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Petts Wood",
        alt: "",
        img: "/img/test-passes/thumbnails/webp/chloe-steel.webp",
        altText: "",
    },
    {
        name: "Kenneth",
        datePassed: "December 2023",
        testCentre: "Bromley",
        firstTime: true,
        area: "Bromley",
        alt: "Test passed with only one driving fault,",
        img: "/img/test-passes/thumbnails/webp/kenneth-masceranhas.webp",
        altText: "with one driving fault",
    },
    {
        name: "Cristiano",
        datePassed: "December 2023",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Chislehurst",
        alt: "Test passed with zero driving faults, Sidcup 2023",
        img: "/img/test-passes/thumbnails/cristiano-webp/da-silva.webp",
        altText: "with zero driving faults",
    },
    {
        name: "Besmir",
        datePassed: "November 2023",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Sidcup, November 2023",
        img: "/img/test-passes/thumbnails/webp/besmir-hoxha.webp",
    },
    {
        name: "Alex",
        datePassed: "November 2023",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Sidcup, November 2023",
        img: "/img/test-passes/thumbnails/webp/alex-sibley.webp",
    },
    {
        name: "Nyiah",
        datePassed: "April 2022",
        testCentre: "Hither Green",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Hither Green, April 2022",
        img: "/img/test-passes/thumbnails/webp/nyiah-pilgrim.webp",
    },
    {
        name: "Dylan",
        datePassed: "March 2022",
        testCentre: "Hither Green",
        firstTime: false,
        area: "University of Greenwich",
        alt: "Test passed in Hither Green, March 2022",
        img: "/img/test-passes/thumbnails/webp/dylan-bassono.webp",
    },
    {
        name: "Ellie",
        datePassed: "February 2022",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Sidcup, November 2021",
        img: "/img/test-passes/thumbnails/webp/ellie-daniels.webp",
    },
    {
        name: "Ashley",
        datePassed: "November 2021",
        testCentre: "Bromley",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Bromley, November 2021",
        img: "/img/test-passes/thumbnails/webp/ashley-hooker.webp",
    },
    {
        name: "Loryn",
        datePassed: "November 2021",
        testCentre: "Bromley",
        firstTime: true,
        area: "New Eltham",
        alt: "Test passed in Bromley, November 2021",
        img: "/img/test-passes/thumbnails/webp/loryn-hunt.webp",
    },
    {
        name: "Amy",
        datePassed: "November 2021",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Lee Green",
        alt: "Test passed in Sidcup, November 2021",
        img: "/img/test-passes/thumbnails/webp/amy-smith.webp",
    },
    {
        name: "Charlotte",
        datePassed: "November 2021",
        testCentre: "Sidcup",
        firstTime: true,
        area: "New Eltham",
        alt: "Test passed in Sidcup, November 2021",
        img: "/img/test-passes/thumbnails/webp/charlotte-reid.webp",
    },
    {
        name: "Katie",
        datePassed: "October 2021",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Eltham",
        alt: "Test passed in Sidcup, August 2021",
        img: "/img/test-passes/thumbnails/webp/katie-clarkstone.webp",
    },
    {
        name: "Callum",
        datePassed: "August 2021",
        testCentre: "Bromley",
        firstTime: true,
        area: "Chislehurst",
        alt: "Test passed in Bromley, August 2021",
        img: "/img/test-passes/thumbnails/webp/callum-biggins.webp",
    },
    {
        name: "Dan",
        datePassed: "July 2021",
        testCentre: "Bromley",
        firstTime: false,
        area: "central London",
        alt: "Test passed in Bromley, July 2021",
        img: "/img/test-passes/thumbnails/webp/dan-rosenheck.webp",
        altText: "on a sunny Thursday morning",
        id: 10,
    },
    {
        name: "Lucas",
        datePassed: "May 2021",
        testCentre: "Bromley",
        firstTime: true,
        area: "Hither Green",
        alt: "Test passed in Bromley, May 2021",
        img: "/img/test-passes/thumbnails/webp/lucas-dunckley.webp",
        id: 9,
    },
    {
        name: "Rebecca",
        datePassed: "November 2020",
        testCentre: "Bromley",
        firstTime: false,
        area: "Chislehurst",
        alt: "Test passed in Chislehurst, October 2020",
        img: "/img/test-passes/thumbnails/rebecca-boley.png",
        id: 8,
        altText: "just before lockdown #2",
    },
    {
        name: "Ruby",
        datePassed: "October 2020",
        testCentre: "Sidcup",
        firstTime: false,
        area: "Eltham",
        alt: "Test passed in Sidcup, October 2020",
        img: "/img/test-passes/thumbnails/ruby-kessell.png",
        id: 7,
        altText: "in the pouring rain",
    },
    {
        name: "Harry",
        datePassed: "March 2020",
        testCentre: "Bromley",
        firstTime: false,
        area: "Chislehurst",
        alt: "Test passed in Bromley, March 2020",
        img: "/img/test-passes/thumbnails/harry-bryant.png",
        id: 6,
        altText: "with only two driver faults",
    },
    {
        name: "Dominic",
        datePassed: "March 2020",
        testCentre: "Bromley",
        firstTime: false,
        area: "Sidcup",
        alt: "Test passed in Bromley, March 2020",
        img: "/img/test-passes/thumbnails/dominic-mcmillan.png",
        id: 5,
        altText: "in torrential rain",
    },
    {
        name: "Jack",
        datePassed: "February 2020",
        testCentre: "Sidcup",
        firstTime: true,
        area: "Petts Wood",
        alt: "Test passed in Sidcup, Feb 2020",
        img: "/img/test-passes/thumbnails/jack-bennett.png",
        id: 4,
        altText: "",
    },
    {
        name: "Freddy",
        datePassed: "January 2020",
        testCentre: "Hither Green",
        firstTime: true,
        area: "Catford",
        alt: "Test passed in Hither Green, Jan 2020",
        img: "/img/test-passes/thumbnails/freddy-dalby-bowler.png",
        id: 3,
    },
    {
        name: "Dominic",
        datePassed: "January 2020",
        testCentre: "Hither Green",
        firstTime: true,
        area: "Blackheath",
        alt: "Test passed in Hither Green, Jan 2020",
        img: "/img/test-passes/thumbnails/dominic-johnson.png",
        id: 2,
        "alt-text": "",
    },
    {
        name: "Rose",
        datePassed: "January 2020",
        testCentre: "Hither Green",
        firstTime: true,
        area: "Kidbrooke",
        alt: "Test passed in Hither Green, Jan 2020",
        img: "/img/test-passes/thumbnails/rose-smith.png",
        id: 1,
        "alt-text": "",
    },
];

export default drivingTestPasses;
